### PR TITLE
Revert the guided synthesis

### PR DESCRIPTION
**Pull request by Patchethium**
I don't know what's happening but even installing a new virtual machine doesn't get the engine to compile, I guess I rather just give it up.

### CODE REVIEW

**Comment by Hiroshiba** [comment]
Sorry for the late reply. I would like to accept revert for now.

Guided synthethis feature is very dreamy!
If you don't mind, please let me know which part was difficult to implement.
Maybe someone else will follow suit and give it a try.

返信が遅くなりました。とりあえずrevertを受け入れたいと思います。

Guided synthethis機能はとても夢のある機能だと思います！
もしよかったらどのあたりの実装が難しかったか、教えてください。
誰かが後をついで挑戦するかもしれません。

**Comment by Patchethium** [comment]
The implementation isn't hard, you just embed a forced aligner and do some math, but the compiling is a mess I've encountered at least 10 problems before I gave up. For example, the pip-license grabs every package, even the ones outside of a virtual env, and since Linux Mint has some pre-installed python packages, it's a dependency nightmare. Such situation doesn't only happen on this branch, but also on master.

Since there are people can compile the master branch, I can theoretically finally get it to compile, for example, by running a docker image. However, I don't want to mess up with nuitka anymore, trying to compile a scripting language with tons of dependencies is a mistake IMO.

BTW I'm also considering to embed [MFA](https://montreal-forced-aligner.readthedocs.io/en/latest/) in order to replace the buggy Julius, hopefully this feature isn't dead yet.

**Comment by Hiroshiba** [comment]
Thank you! It is very informative.

By the way, besides Julius, there is another alignment tool called SHIRO. This one is made by Lua. You also need to create a model with some kind of data set. Maybe it could be useful...?
https://github.com/Sleepwalking/SHIRO


ありがとうございます！！とても勉強になります。

そういえばJulius以外にも、SHIROというアライメントツールがあります。こちらはLua製です。また、何かしらのデータセットを用いてモデルを作る必要もあります。もしかしたら役立つかも･･･？
https://github.com/Sleepwalking/SHIRO

**Comment by Patchethium** [comment]
> https://github.com/Sleepwalking/SHIRO

Oh it's Kanru Hua's work! It's also him made the Synthesizer V and VOICEPEAK.
I took a look but unfortunately, it's released under GPL, which means we are not able to utilize it here :cry:
Anyway, thanks for the information!

**Pull request merged**
